routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/postulantes', 'PostulanteController')->middleware(['auth']);
Route::resource('/antecedentes', 'AntecedenteController')->middleware(['auth']);

Route::get('/postulante/perfil', 'PostulanteController@perfil')->middleware('auth')->name('postulante.perfil');

app/Antecedente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Antecedente extends Model
{
	    // protected $table = 'antecedentes';

	 protected $fillable = [
        'descripcion',
        'fecha_emision',
        'institucion_otorgante',
        'user_id',
    ];

	 public function user()
	    {
	        return $this->belongsTo('App\User', 'user_id');
	    }
}

app/Cargo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cargo extends Model
{
    //
}

app/CentroJudicial.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CentroJudicial extends Model
{
    //
}

app/Concurso.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Concurso extends Model
{
    //
}

app/Fuero.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Fuero extends Model
{
    //
}

app/Movimiento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Movimiento extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'apellido',
        'nombre',
        'dni',
        'email',
        'password',
        'fecha_nac',
        'domicilio',
        'telefono',
        'fecha_titulo',
        'universidad_otorgante',
        'admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'admin' => 'boolean',
    ];

    public function isAdmin()
    {
        return $this->admin;
    }

    public function antecedentes()
    {
        return $this->hasMany('App\Antecedente');
    }

    public function concursos()
    {
        return $this->belongsToMany('Concurso');
    }

    public function getNombre()
    {
        return $this->apellido.', '.$this->nombre;
    }
}

app/Http/Controllers/AntecedenteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Antecedente;
use App\User;
use Illuminate\Support\Facades\Auth;

class AntecedenteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $this->validate($request, array(
          'descripcion' => 'required|max:100',
          'fecha_emision' => 'required|date',
          'institucion_otorgante' => 'required|max:50',
        ));

        $antecedente = new Antecedente();
        $antecedente->descripcion = $request->descripcion;
        $antecedente->fecha_emision = $request->fecha_emision;
        $antecedente->institucion_otorgante = $request->institucion_otorgante;
        $antecedente->user_id = Auth::user()->id;
        $antecedente->save();
        return redirect(route('postulante.perfil'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostulanteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Auth;
use App\Antecedente;

class PostulanteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $postulantes = User::orderby('apellido')->orderby('nombre')->paginate(25);

        return view('postulantes.index')->withPostulantes($postulantes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $postulante = User::findOrFail($id);
        return view('postulantes.show')->withPostulante($postulante);
    }

    public function perfil()
    {
        $postulante = User::find(Auth::user()->id);
        $antecedentes = User::find($postulante->id)->antecedentes();
        return view('postulantes.dashboard')->withPostulante($postulante)->withAntecedentes($antecedentes);
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/postulantes/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="panel">
                <div class="panel-header">
                  <h3>Perfil de postulante {{ $postulante->getNombre() }}</h3>
                </div>

                <div class="panel-body">
                  <h4>DNI: {{ $postulante->dni }}</h4>
                  <h4>Email: {{ $postulante->email }}</h4>
                  <h4>Fecha de nacimiento: {{ $postulante->fecha_nac }}</h4>
                  <h4>Domicilio: {{ $postulante->domicilio }}</h4>
                  <h4>Teléfono: {{ $postulante->telefono }}</h4>
                  <h4>Fecha de expedición de título: {{ $postulante->fecha_titulo }}</h4>
                  <h4>Universidad otorgante: {{ $postulante->universidad_otorgante }}</h4>
                </div>
                <div class="panel-footer">
                  <h4>Antecedentes</h4>
                    <table class="table table-hover">
                      <thead>
                        <tr>
                            <td>Descripción</td>
                            <td>Institucion</td>
                            <td>Fecha de Emisión</td>
                        </tr>
                      </thead>
                      <tbody>
                      @foreach($postulante->antecedentes as $antecedente)
                        <tr>
                          <td>{{$antecedente->descripcion}}</td>
                          <td>{{$antecedente->institucion_otorgante}}</td>
                          <td>{{$antecedente->fecha_emision}}</td>
                        </tr>                    
                      @endforeach          
                      </tbody>
                    </table>
    
                  
                </div>
            </div>
        </div>
        <div class="col-md-4">
          <div class="panel">
              <div class="panel-header">
                <h3>Agregar antecedente</h3>
            </div>
            <div class="panel-body">
              <form method="POST" action="{{ route('antecedentes.store') }}">
                  {{ csrf_field() }}
                
                  <div class="form-group row">
                      <label for="descripcion" class="col-md-12 col-form-label text-md-left">{{ __('Descripción') }}</label>
                      <div class="col-md-12">
                          <input id="descripcion" type="text" class="form-control{{ $errors->has('descripcion') ? ' is-invalid' : '' }}" name="descripcion" value="{{ old('descripcion') }}" required autofocus>

                          @if ($errors->has('descripcion'))
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $errors->first('descripcion') }}</strong>
                              </span>
                          @endif
                      </div>
                  </div>

                  <div class="form-group row">
                      <label for="fecha_emision" class="col-md-12 col-form-label text-md-left">{{ __('Fecha de emisión') }}</label>
                      <div class="col-md-12">
                          <input id="fecha_emision" type="date" class="form-control{{ $errors->has('fecha_emision') ? ' is-invalid' : '' }}" name="fecha_emision" value="{{ old('fecha_emision') }}" required autofocus>

                          @if ($errors->has('fecha_emision'))
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $errors->first('fecha_emision') }}</strong>
                              </span>
                          @endif
                      </div>
                  </div>

                  <div class="form-group row">
                      <label for="institucion_otorgante" class="col-md-12 col-form-label text-md-left">{{ __('Institución otorgante') }}</label>
                      <div class="col-md-12">
                          <input id="institucion_otorgante" type="text" class="form-control{{ $errors->has('institucion_otorgante') ? ' is-invalid' : '' }}" name="institucion_otorgante" value="{{ old('institucion_otorgante') }}" required autofocus>

                          @if ($errors->has('institucion_otorgante'))
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $errors->first('institucion_otorgante') }}</strong>
                              </span>
                          @endif
                      </div>
                  </div>
                  &nbsp
                  <div class="form-group row mb-0">
                      <div class="col-md-12">
                          <button type="submit" class="btn btn-block btn-primary">
                              {{ __('Agregar antecedente') }}
                          </button>
                      </div>
                  </div>
                </form>
            </div>
          </div>
        </div>
    </div>
</div>
@endsection

resources/views/postulantes/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
          <table class="table table-striped">
            <thead class="thead-dark">
              <tr>
                <th>Nombre completo</th>
                <th>DNI</th>
                <th>Email</th>
                <th>Fecha de nacimiento</th>
                <th>Domicilio</th>
                <th>Teléfono</th>
                <th>Acción</th>
              </tr>
            </thead>
            <tbody>
              @foreach($postulantes as $postulante)
              <tr>
                <th>{{$postulante->apellido.', '.$postulante->nombre}}</th>
                <th>{{$postulante->dni}}</th>
                <th>{{$postulante->email}}</th>
                <th>{{$postulante->fecha_nac}}</th>
                <th>{{$postulante->domicilio}}</th>
                <th>{{$postulante->telefono}}</th>
                <th><a href="{{route('postulantes.show', $postulante->id)}}" class="btn btn-primary">Ver</a></th>
              </tr>
              @endforeach
            </tbody>
          </table>
          {{ $postulantes->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/postulantes/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h3>Datos del postulante {{$postulante->getNombre()}}</h3>
      <hr>
    </div>
  </div>
    <div class="row">
        <div class="col-md-8">
          <h4>DNI: {{$postulante->dni}}</h4>
          <h4>Email: {{$postulante->email}}</h4>
          <h4>Fecha de nacimiento: {{$postulante->fecha_nac}}</h4>
          <h4>Domicilio: {{$postulante->domicilio}}</h4>
          <h4>Teléfono: {{$postulante->telefono}}</h4>
          <h4>Fecha de expedición de título: {{$postulante->fecha_titulo}}</h4>
          <h4>Universidad otorgante: {{$postulante->universidad_otorgante}}</h4>
          
          <h4>Antecedentes</h4>
                    <table class="table table-hover">
                      <thead>
                        <tr>
                            <td>Descripción</td>
                            <td>Institucion</td>
                            <td>Fecha de Emisión</td>
                        </tr>
                      </thead>
                      <tbody>
                      @foreach($postulante->antecedentes as $antecedente)
                        <div class="row">
                          <td>{{$antecedente->descripcion}}</td>
                          <td>{{$antecedente->institucion_otorgante}}</td>
                          <td>{{$antecedente->fecha_emision}}</td>                    
                      @endforeach          
                      </tbody>
                    </table>
        </div>
      </div>
</div>
@endsection